explicit path to string conversion for Windows
Apparently an implicit conversion via `=` does not exist on Windows:

D:\a\Soar\Soar\Core\CLI\src/cli_CommandLineInterface.cpp(93): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::filesystem::path' (or there is no acceptable conversion)
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\xstring(1429): note: could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const _Elem)'
        with
        [
            _Elem=char
        ]